<meta charset="UTF-8"> <!-- Important afin d'afficher le "é" correctement dans le sommaire -->
<div class="article-subtitle" id="cafe1970">Les cafés montois 1970</div>
<div class="article-content">
    <p>Si je vous propose ce nouveau sujet, c’est dans un but purement historique, et surtout pour mettre en évidence l’évolution de la « vie en Polytech » sur un peu plus de trois décennies … j’espère seulement, et sincèrement, ne pas provoquer trop de regrets nostalgiques !</p>
    <p>En ces temps bénis en effet (je parle des années 70) et comme dans pas mal d’autres villes universitaires, le folklore estudiantin faisait partie intégrante de la vie montoise et était très bien accepté, voire même apprécié, par la grande majorité de la population. J’aurai sans doute l’occasion d’y revenir, mais retenez dès à présent que vous pouviez traverser la Ville de part en part, seul, saoûl comme un cochon et en braillant tout votre répertoire de chansons paillardes, les plus grands risques qui vous menaçaient étaient bien de trébucher sur une poubelle mal rangée, ou de glisser sur une crotte de chien oubliée ! La penne, le tablier et la chope autour du cou (oui oui, la vraie chope en verre !) attiraient de sincères et sympathiques sourires, et combien de fois n’ai-je pas lu dans des regards inconnus, une réelle connivence et une véritable envie d’en « faire partie aussi » ? Les Autorités et la maréchaussée elle-même acceptaient ce folklore, et je ne me souviens que de très rares interventions de nos policiers de l’époque … oserais-je ajouter qu’ils savaient, eux, faire la distinction entre un étudiant gentiment chahuteur et un voyou en puissance ? (Merci à la censure de ne pas me couper, cet avis est personnel et n’engage donc que ma petite personne).</p>
    <p>« O tempora, o mores », comme disait l’autre … il y a de celà 2000 ans !</p>
    <p>Toujours est-il que dans un tel environnement, il était tout naturel que notre bonne vieille Cité du Doudou soit parsemée de bistrots à fréquentation presqu’exclusivement estudiantine … Les Wawas avaient les leurs, les Fucam beaucoup moins (vu leur éloignement géographique), et je ne parlerai donc que des cafés à tendance franchement Polytech … je compte bien évidemment sur mes contemporains et prédécesseurs pour corriger les éventuelles erreurs et inévitables oublis.</p>
    <p>Il m’est quasiment impossible de les classer dans un certain « ordre » (par chronologie, par importance, etc…), mais je m’efforcerai de citer à chaque fois: le nom officiel suivi du prénom du (des) patron(s), de 0 à 3 étoiles (entre parenthèses) censées représenter la fréquence des guindailles qui s’y déroulaient, la situation géographique, et divers commentaires et faits divers qui s’y sont déroulés.</p>
    <p>Allons, courage Verjus, faut que tu te lances !</p>
    <br><p>– « Chez Andréa » (**), rue de la Clef (en face du Marché aux Herbes), fermé en 74 ou 75; patronne assez pulpeuse qui devait avoir pas mal de « kilomètres au compteur » … oufti !</p>
    <p>– « L’Archiduc » ou « Chez Yerno » (orthographe non-garantie), (***), à une trentaine de mètres à main gauche quand vous prenez la rue de Nimy en venant de la Grand-Place. Très nombreuses guindailles et point de chute naturel de tous ceux qui rentraient à la Cité le dimanche soir …</p>
    <p>– « Le Beaulieu », dont je ne me souviens que du dernier patron Robert Vasseur (dit Vibro, parce que « ma soeur »), (***), sur la Grand Place et à votre droite quand vous faites face au Théâtre, doit s’appeler « le Central » actuellement. Eut l’honneur d’avoir ses toilettes obturées par ma penne, que j’avais naïvement échangée avec celle de « Manu », un IRAM (ISIC) indigne de ma confiance à l’époque de la « Polyram ». Rien à voir avec Manu Janssen, je précise !</p>
    <p>– « L’Oeil de Boeuf » ou « Chez Denise », (*), à droite de l’entrée des anciens abattoirs. Repaire des Borains et des Centraux qui ne kottaient pas à la Cité, ainsi bien sûr que des chevilleurs de l’abattoir. Style très rustique, patronne assez agée et particulièrement sympa, doit avoir fermé en 80 ?</p>
    <p>– « The two Lions » ou « Chez Sammy », (***), à main gauche dans la rue Léopold 1er en venant de la gare, presqu’en face du monument avec un globe terrestre dont je ne connais plus le nom. Théâtre de la toute première interprétation de Chant de la Fac, le jour même où il fut écrit (octobre 75).</p>
    <p>– « Chez Bobonne », (), à main gauche quand vous pénétrez sur la Grand-Place en venant de la rue de la Chaussée. Mêmes remarques que pour l’Oeil de Boeuf, les chevilleurs en moins …</p>
    <p>– « Le Pilote » (Chez Albert, puis chez Willy), (*), juste au coin en face de la Cité quand vous allez à Houdain. On y servait de la « Supra », tous les autres étant « Jupiler » ! Jouissait évidemment de l’effet de proximité, mais n’a existé que 4 ou 5 ans …</p>
    <p>– « Le Pylône » ou « Chez Alain (et Christiane) », (**), ouvert en 76 ou 77, existe toujours au coin de la rue des Arquebusiers et de l’avenue Frère Orban, et possède d’ailleurs toujours le même mobilier !!! Christiane y faisant la petite restauration, j’y ai donc passé des journées entières à taper la carte au son inoubliable de Pink Floyd. A carrément changé de style avec le départ d’Alain en 1979 …</p>
    <p>– « Le Café des Boulevards » ou « Chez Nado », (*), au coin juste en face de la banque quand vous allez de la Cité aux labos du Dolez (actuellement le siège d’une compagnie d’assurances, je pense?). Très fréquenté sur le coup de 15h quand on avait labo, ou quand vous aviez envie d’une partie de billard « à bouchons ». Un hangar à l’arrière nous accueillait après le Baptême, et servait d’ailleurs à la préparation de la « potion magique » que vous connaissez bien! La vanne d’une cuve à mazout y fut arrachée à la fin d’un souper Carolo … bonjour les dégâts !</p>
    <br><p>Voilà, je pense avoir fait le tour … J’ajouterai simplement que les 4 premiers estaminets de la liste constituaient les étapes du célèbre « Rallye Cafés » de ma bleusaille, mais il s’agit d’un autre débat … !</p>
    <p>Allez, à plusss !</p>
    <p>Votre dévoué,</p>
    <div class="sources italic-text">Jean-Claude "Verjus" Versieux, ancien Carolo, 134ème promotion (peut-être un peu avant)</div>
</div>