<meta charset="UTF-8"> <!-- Important afin d'afficher le "é" correctement dans le sommaire -->
<div class="article-subtitle" id="lune1970">Le Choléra - 1971</div>
<div class="article-content">
    <p>«Traditionnellement, les étudiants de la Faculté organisent dans la ville de Mons une « grosse » blague pendant la période de bleusaille. En 1971, cette blague a eu lieu le mercredi 13 octobre.
        Comme chaque année, la Fédé et le Comité des Fêtes dont je faisais partie ont fait un exercice de « brainstorming » pour décider en quoi consisterait la blague généralement très appréciée. Il a été décidé d’organiser sur la Grand-Place une vaccination contre le choléra à l’intention des Montois et des différentes écoles de la ville. En effet, début des années 70, l’épidémie menaçait l’Europe et touchait fortement l’Afrique. Une telle vaccination avait donc de fortes chances d’être acceptée par la population. Un avis provenant du CTB, soit le Centre de Thérapeutique Bactérienne (mais les anciens donnaient à ce sigle une autre signification !) a donc été rédigé pour informer les Montois de l’importance de cette vaccination et des modalités pratiques pour en bénéficier. Les étudiants se sont chargés de distribuer largement et discrètement ce document dans les boîtes aux lettres des habitants. Des tentes « sanitaires » c'est-à-dire similaires à celles de la Croix-Rouge ont été louées et munies du sigle « CTB ». De même pour le mobilier : tables, chaises et bureaux destinés à équiper les tentes qu’il a fallu monter sur la Grand-Place la veille de la blague. Des étudiants de la Faculté ainsi que leurs copines ont été choisis pour jouer le rôle de médecins, infirmières et infirmiers pour le jour de la vaccination. Ils ont reçu des uniformes adéquats et des répétitions ont évidemment eu lieu. Tous ces préparatifs ont bien sûr dû se faire dans la plus grande discrétion : seule une poignée d’étudiants étaient au courant.
        Les Montois se sont massivement rendus à cette vaccination : elle était crédible et le « corps médical » étudiant avait une apparence de sérieux ! Après avoir décliné leur identité, les gens recevaient le vaccin par une cuillère (contenant en fait un sirop !) ainsi qu’un certificat de vaccination à l’apparence tout aussi officielle. Très peu se sont rendu compte qu’il s’agissait d’une blague !
        Nous gardons sans aucun doute un excellent souvenir de ce canular dont le seul but était de faire rire ! »
        -Richard SHEEREN Promotion 1972
        Source: Polytech-mons-alumni.be. Le Journal de l’AIMs Avril-Mai-Juin 2022. Merci l'AIMs ! Fb comhisto</p>
</div>